Documentation/pfdoc 0001
inxudianz/Project-Famili pull request #11
Opened 2020-06-30 13:49 UTC by SetyaG

### Description
Updated the issues and pull requests template

**Files affected**:
- issue_template.md
- pull_request_template.md

Resolving issue #9

2020-07-01 07:56 UTC, inxudianz requested changes
Please readjust the template using the git convention in the wiki

2020-07-07 12:11 UTC, SetyaG commented
Resolved

2020-07-07 12:31 UTC, inxudianz requested changes

2020-07-07 12:31 UTC, inxudianz commented on .github/issue_template.md
> +
change format to:

issue type : [ in git convention]

Priority: <low med high>

User Story:
<link to user story ( can be either trello or figma)>

Expected date:
start:
end:

Notes:

2020-07-07 12:31 UTC, inxudianz commented on .github/pull_request_template.md
> +### Todos
todos will be
UI
Coordinator
Network
Tests
Documentation

2020-07-07 12:31 UTC, inxudianz commented on .github/pull_request_template.md
> +### Deploy Notes
change deploy notes and steps to reproduce with
Screenshot / Video:
divided into
UI
Network
and tests

2020-07-07 12:31 UTC, inxudianz commented on .github/pull_request_template.md
> +### Related Pull Requests (PRs)
change to link to user story and link to figma related to the pr

2020-07-07 12:31 UTC, inxudianz commented on .github/pull_request_template.md
> +
remove line 1-10

2020-07-07 12:31 UTC, inxudianz commented on .github/pull_request_template.md
> +Closes issue **#[ISSUE NUMBER]**
place it in top with related user story and figma

2020-07-07 12:31 UTC, inxudianz commented on .github/pull_request_template.md
> +## Impacted Areas in Application
change impacted areas to notes:
can contains technical debt, blocker, etc

2020-07-09 07:46 UTC, inxudianz approved these changes

2020-07-09 07:57 UTC, merged