[PFBF3-0002] Notification Refactor
inxudianz/Project-Famili pull request #122
Opened 2020-11-20 20:19 UTC by SetyaG

Closes #113 
***
## Description
Refactor notification to make it tidier, and do renaming on specified files and functions

## Related Links
List related PRs against other branches:

List | link
------ | ------
User Story | [link]()
Figma | [link]()
Issue | [link](#113 )

## Todos
- [X] UI
- [ ] Coordinator
- [ ] Network
- [ ] Tests
- [X] Documentation

## Screenshot / Video
Screenshot consisting of changes made on this branch.

### UI Changes
UI related changes will be shown here (can be either screenshot or video format)

### Network Status
Network related changes will be shown here (screenshot of request status)

### Test Coverage
Test coverage result for designated changes will be shown here (screenshot of coverage)

## Notes
- No data has been found when using mock API for Sprint 2 (so can't see how it looks when there are data found)

2020-11-21 05:51 UTC, SetyaG commented
![HomeNotificationRefactor](https://user-images.githubusercontent.com/45433184/99868780-910b6f80-2c00-11eb-9c0a-242ebad61e95.gif)

2020-11-22 12:10 UTC, inxudianz requested changes

2020-11-22 12:10 UTC, inxudianz commented on Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationMessageViewModel+Network.swift
Rename the filename to match class name

2020-11-22 12:10 UTC, inxudianz commented on Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationNewsViewModel+Network.swift
Rename file to match class name

2020-11-22 12:25 UTC, SetyaG commented on Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationNewsViewModel+Network.swift
moved to a new file name

2020-11-22 12:25 UTC, SetyaG commented on Laundron-User/LUFeature/LUHome/LUHome/LUHome/HomeNotification/HomeNotificationMessageViewModel+Network.swift
moved to a new file name

2020-11-23 10:06 UTC, inxudianz approved these changes

2020-11-23 10:07 UTC, merged