[PFSP1-0001] Initial Screen
inxudianz/Project-Famili pull request #30
Opened 2020-07-27 07:31 UTC by evan03121998

[PFSP1-0001] Initial Screen
Closes #20
***
## Description
Initial Screen View

## Related Links
List related PRs against other branches:

List | link
------ | ------
User Story | [link]()
Figma | [link]()
Issue | [link]()

## Todos
- [X] UI
- [ ] Coordinator
- [ ] Network
- [ ] Tests
- [ ] Documentation

## Screenshot / Video
Screenshot consisting of changes made on this branch.

### UI Changes
UI related changes will be shown here (can be either screenshot or video format)

### Network Status
Network related changes will be shown here (screenshot of request status)

### Test Coverage
Test coverage result for designated changes will be shown here (screenshot of coverage)

## Notes
Additional notes that you have either technical debt, blocker, etc.

2020-07-27 07:34 UTC, inxudianz requested changes

2020-07-27 07:34 UTC, inxudianz commented on MainApp/MainApp/Feature/Splash/InitialScreenViewController.swift
> +    */
comment2 dihapus bang

2020-07-27 07:34 UTC, inxudianz commented on MainApp/MainApp/Feature/Splash/InitialScreenViewController.swift
> +        // Do any additional setup after loading the view.
commend dihapus

2020-07-27 07:34 UTC, inxudianz commented on MainApp/MainApp/Feature/Splash/InitialScreenViewController.swift
> +    @IBOutlet weak var initialScreenArrowButton: UIButton!
buat IBAction untuk navigate to next screen sama buat coordinator

2020-07-27 07:35 UTC, evan03121998 commented on MainApp/MainApp/Feature/Splash/InitialScreenViewController.swift
> +    */
g

2020-07-27 07:36 UTC, evan03121998 commented on MainApp/MainApp/Feature/Splash/InitialScreenViewController.swift
> +        // Do any additional setup after loading the view.
g

2020-07-27 07:38 UTC, robbyaww submitted a review, later dismissed

2020-07-27 09:51 UTC, inxudianz requested changes
Space - space yang berlebihan dihapus

Coordinator related file taro di Coordinator/Feature group

2020-07-28 15:44 UTC, inxudianz requested changes
Login coordinator ga ke commit

2020-07-28 15:50 UTC, inxudianz requested changes

2020-07-28 15:50 UTC, inxudianz commented on MainApp/MainApp/Feature/Login/LoginViewController.swift
> +        viewModel?.gotoHome()
logic login email sama gitu2 nya di handle juga ya, tutorialnya entar besok sore

2020-07-29 07:24 UTC, robbyaww submitted a review, later dismissed

2020-08-07 04:58 UTC, inxudianz requested changes

2020-08-07 04:58 UTC, inxudianz commented on MainApp/MainApp/FeatureNetwork/SampleNetwork/LoginNetwork.swift
> +
Pindahin LoginNetwork di group LoginNetwork

2020-08-07 04:58 UTC, inxudianz commented on MainApp/MainApp/FeatureNetwork/SampleNetwork/LoginNetwork.swift
> +import RxSwift
RXSwift no need to be imported

2020-08-07 04:58 UTC, inxudianz commented on MainApp/MainApp/Network/Service/LoginService.swift
> +            return .plainRequest
login karena ada pake model pakenya parameteredRequest

2020-08-07 04:58 UTC, inxudianz commented on MainApp/MainApp/Network/Path/FeaturePath/Sample/LoginPath.swift
> +//  Created by Evan Christian on 06/08/20.
pindahin ke FeaturePath/Auth/<File>

2020-08-07 04:58 UTC, inxudianz commented on MainApp/MainApp/Network/Path/FeaturePath/Sample/LoginSubPath.swift
> +
pindahin ke FeaturePath/Auth/<File>

2020-08-09 13:42 UTC, inxudianz approved these changes

2020-08-09 13:43 UTC, merged