[PFSP2-0006] Privacy Policy
inxudianz/Project-Famili pull request #85
Opened 2020-09-21 04:28 UTC by SetyaG

Closes #63 
***
## Description
Create the Privacy Policy page

## Related Links
List related PRs against other branches:

List | link
------ | ------
User Story | [link]()
Figma | [link]()
Issue | [link](#63 )

## Todos
- [X] UI
- [ ] Coordinator
- [ ] Network
- [X] Tests
- [ ] Documentation

## Screenshot / Video
Screenshot consisting of changes made on this branch.

### UI Changes
UI related changes will be shown here (can be either screenshot or video format)

### Network Status
Network related changes will be shown here (screenshot of request status)

### Test Coverage
Test coverage result for designated changes will be shown here (screenshot of coverage)
<img width="1440" alt="Screen Shot 2020-09-21 at 11 05 14" src="https://user-images.githubusercontent.com/45433184/93732873-e37ede80-fc05-11ea-8ab3-2dc6b9d8a751.png">

## Notes
Additional notes that you have either technical debt, blocker, etc.

2020-09-21 06:01 UTC, inxudianz requested changes
Please provide Gif of the finished product

2020-09-21 06:04 UTC, inxudianz requested changes
Please provide Gif of the finished product

2020-09-21 06:04 UTC, inxudianz commented on MainApp/MainApp/Feature/Profile/PrivacyPolicy/PrivacyPolicyViewController.swift
> +    @IBOutlet weak var PrivacyPolicyLabel: UILabel!
Please use the designated font

2020-09-23 08:57 UTC, SetyaG commented on MainApp/MainApp/Feature/Profile/PrivacyPolicy/PrivacyPolicyViewController.swift
> +    @IBOutlet weak var PrivacyPolicyLabel: UILabel!
done

2020-09-23 09:06 UTC, SetyaG commented
![privacy policy](https://user-images.githubusercontent.com/45433184/93991556-07d1eb00-fdbf-11ea-8fc0-a70cd9ba609a.gif)

2020-09-23 10:43 UTC, merged