[PFSP2-0005] Terms of Service
inxudianz/Project-Famili pull request #86
Opened 2020-09-21 04:30 UTC by SetyaG

Closes #62 
***
## Description
Create the Terms of Service page

## Related Links
List related PRs against other branches:

List | link
------ | ------
User Story | [link]()
Figma | [link]()
Issue | [link](#62)

## Todos
- [X] UI
- [ ] Coordinator
- [ ] Network
- [X] Tests
- [ ] Documentation

## Screenshot / Video
Screenshot consisting of changes made on this branch.

### UI Changes
UI related changes will be shown here (can be either screenshot or video format)

### Network Status
Network related changes will be shown here (screenshot of request status)

### Test Coverage
Test coverage result for designated changes will be shown here (screenshot of coverage)
<img width="1440" alt="Screen Shot 2020-09-21 at 12 21 18" src="https://user-images.githubusercontent.com/45433184/93732913-1923c780-fc06-11ea-9752-58af2abd4f05.png">

## Notes
Additional notes that you have either technical debt, blocker, etc.

2020-09-21 06:45 UTC, inxudianz requested changes
fix unit test as well as upload gif

2020-09-21 06:45 UTC, inxudianz commented on MainApp/MainApp/Feature/Profile/Terms of Service/TermsOfServiceController.swift
> +    @IBOutlet weak var TOSLabel: UILabel! {
tos need to be lowercased

2020-09-23 08:56 UTC, SetyaG commented on MainApp/MainApp/Feature/Profile/Terms of Service/TermsOfServiceController.swift
> +    @IBOutlet weak var TOSLabel: UILabel! {
done

2020-09-23 09:06 UTC, SetyaG commented
![terms of service](https://user-images.githubusercontent.com/45433184/93991650-1cae7e80-fdbf-11ea-898c-2a14cf2b3233.gif)

2020-09-23 09:21 UTC, SetyaG commented
Unit test fixed
<img width="1399" alt="Screen Shot 2020-09-23 at 17 20 25" src="https://user-images.githubusercontent.com/45433184/93993377-4072c400-fdc1-11ea-9ebd-2fdd9dff965a.png">

2020-09-23 10:36 UTC, merged